Env: "prod"

DatabaseSettings:
  DatabaseURI: "root:Furkan7937.@tcp(127.0.0.1:3306)/graduation?parseTime=True&loc=Local"
  DatabaseName: "graduationproject"
  Username: "root"
  Password: "Furkan7937."

NewRelicSettings:
  LicenseKey: "YOUR_LICENSE_KEY"
  AppName: "YOUR_APP_NAME"

JwtSettings:
  SecretKey: "MY_PROD_SECRET_KEY"